### ISSUE TITLE
Pie chart not shown for new user

### ISSUE THREAD

**Issue by shashank-madan** [aditikilledar/burnout-proj3#76]
For a newly registered user or a user who has not updated their profile with height, weight, sex and activity level fields, tdee cannot be calculated and pie chart does not render.

Suggestion:
Display a message or graphic in place of the pie chart prompting users to update the necessary fields

**Comment by srina1h** [comment]
Why not update sign in form to reflect initial information. Collect info on ramp flow. Might make every other calculation simpler downstream.

**Comment by shashank-madan** [comment]
That is a good idea. But I think it having this on the sign-up page might be better.

**Comment by aditikilledar** [comment]
Future scope
